# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#

title: I ❤︎ building teams | Delano Mandelbaum
author: Delano
email: delano@onetimesecret.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a software engineering manager known for building healthy, high-performing teams.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://delanotes.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: solutious
github_username:  delano

# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Exclude from processing.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list". Excluded items can be processed by explicitly
# listing the directories or their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
