destination: ./_site
auto:        true
lsi:         false
server_port: 4000
pygments:    true
markdown:    kramdown
permalink:   pretty
highlighter: chartreuse
kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5
