# Based on https://github.com/helaili/jekyll-action

name: "Update website (aftermarket action)"

on:
  gollum:

  push:
    branches:
      - $default-branch
      - develop

  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
      - unlabeled

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as
# we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:

  ##
  # Builds & deploys the Jekyll site to GitHub Pages.
  #
  # See: https://github.com/helaili/jekyll-action
  #
  github-pages:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      # Enable caching of Ruby gems
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: helaili/jekyll-action@2.5.0    # Choose any one of the Jekyll Actions
        with:                                # Some relative inputs of your action
          target_branch: gh-pages
          keep_history: true
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
          JEKYLL_ENV: production
